=== eltntawy/Java-Labs/src/main/java/xml/lab2/library.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


	<xs:attributeGroup name="title_G"></xs:attributeGroup>
	<xs:attribute name="title" type="xs:string"></xs:attribute>

	<xs:attributeGroup name="summary_G"></xs:attributeGroup>
	<xs:attribute name="summary" type="xs:string" />

	<xs:attributeGroup name="ISBN_G"></xs:attributeGroup>
	<xs:attribute name="ISBN" type="xs:string"></xs:attribute>

	<xs:attributeGroup name="author_G"></xs:attributeGroup>
	<xs:attribute name="author" type="xs:string"></xs:attribute>


	<xs:attributeGroup name="preface_G"></xs:attributeGroup>
	<xs:attribute name="preface" type="xs:string"></xs:attribute>

	<xs:attributeGroup name="name_G"></xs:attributeGroup>
	<xs:attribute name="name" type="xs:string"></xs:attribute>

	<xs:attributeGroup name="location_G"></xs:attributeGroup>
	<xs:attribute name="location" type="xs:string"></xs:attribute>

	<xs:attributeGroup name="description"></xs:attributeGroup>
	<xs:attribute name="description" type="xs:string"></xs:attribute>


	<xs:complexType name="section">
		<xs:sequence>
			<xs:element name="paragraph" type="xs:string" />
		</xs:sequence>

		<xs:attribute ref="title"></xs:attribute>
	</xs:complexType>




	<xs:complexType name="chapter">
		<xs:sequence>
			<xs:element name="section" />
		</xs:sequence>

		<xs:attribute ref="title"></xs:attribute>
		<xs:attribute ref="summary"></xs:attribute>
	</xs:complexType>




	<xs:complexType name="part">
		<xs:sequence>
			<xs:element name="chapter" type="chapter" />
		</xs:sequence>

		<xs:attribute ref="title"></xs:attribute>

	</xs:complexType>




	<xs:complexType name="parts">
		<xs:sequence>
			<xs:element name="part" type="part" />
		</xs:sequence>
	</xs:complexType>




	<xs:complexType name="book">
		<xs:sequence>
			<xs:element name="parts" type="parts" />
		</xs:sequence>

		<xs:attribute ref="title"></xs:attribute>
		<xs:attribute ref="ISBN"></xs:attribute>
		<xs:attribute ref="author"></xs:attribute>
		<xs:attribute ref="preface"></xs:attribute>
	</xs:complexType>




	<xs:complexType name="library">
		<xs:sequence>
			<xs:element name="book" type="book" />
		</xs:sequence>

		<xs:attribute ref="name"></xs:attribute>
		<xs:attribute ref="location"></xs:attribute>
		<xs:attribute ref="description"></xs:attribute>

	</xs:complexType>


	<xs:complexType name="libraries">
		<xs:sequence>
			<xs:element name="library" type="library" />
		</xs:sequence>

	</xs:complexType>

	<xs:element name="libraries" type="libraries"></xs:element>

</xs:schema>

=== eltntawy/Java-Labs/src/main/java/xml/lab2/library.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE library SYSTEM "library.dtd"> -->
<libraries xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="library.xsd" >

	<library name="" location="" description="">
		<book ISBN="" title="" author="" preface="">
			<parts>
				<part title="">
					<chapter title="" summary="">

						<section title="">
							<paragraph>
							
							</paragraph>
						</section>
						
						<section title="">
							<paragraph>
							
							</paragraph>
						</section>
					</chapter>
				</part>
			</parts>
		</book>
	</library>
	</libraries>
