=== eltntawy/Java-Labs/src/main/java/xml/api/lab2/XmlSchema.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:complexType name="MsgBody">
        <xs:sequence  > 
            <xs:element name="from" type="xs:string" ></xs:element>
            <xs:element name="to" type="xs:string"  minOccurs="2" maxOccurs="2" > </xs:element>
        
            <xs:element name="data" type="xs:string" > </xs:element>
            <xs:element name="body" type="xs:string" > </xs:element>
        </xs:sequence>
        
        
    </xs:complexType>
    
    <xs:complexType name="MyMsg">
        <xs:sequence  >
            <xs:element name="header"  type="xs:string" ></xs:element>
            <xs:element name="Msg" type="MsgBody" ></xs:element>
        </xs:sequence>
        
    </xs:complexType>
    
    <xs:element name="MyMsg" type="MyMsg" />
</xs:schema>

=== eltntawy/Java-Labs/src/main/java/xml/api/lab2/XMLDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<MyMsg
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='file:/home/eltntawy/ITI/Java/Java-Labs/src/main/java/xml/api/lab2/XmlSchema.xsd'>
    
    
    <header>
            Message from Sender
    </header>
    <Msg>
        <from>eltntawy@gmail.com</from>
        <to>eltntawy@gmail.com</to>
        <to>eltntawy@gmail.com</to>
        <data>This is message Data</data>
        <body>This is message Body</body>
    </Msg>
    
</MyMsg>
